//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_bán_hàng__đồ_án_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviec
    {
        public int id_service { get; set; }
        public string name_service { get; set; }
        public Nullable<double> price { get; set; }
        public string function { get; set; }
    }
}
